"""Fetch the GitHub topics for every repository in the shared manifest and
publish one JSON file per repository through a single pull request.

Topics are repository settings, not code, so changing them does not move a
branch head -- the manifest orchestrators' commit-hash check would never pick
them up. This job reads them straight from the GitHub API on its own schedule
instead. No LLM agent is involved.

The output deliberately carries no timestamp, so a run where no topics changed
writes identical files and opens no pull request.

Required environment variables:
    GITHUB_PR_TOKEN     Token with contents + pull-requests write access to the
                        manifest repository (talentsuite-atlas). Also used
                        to read topics unless REPO_TOPICS_TOKEN is set.

Optional environment variables:
    REPO_TOPICS_TOKEN   Token with metadata read access to the manifest
                        repositories, for when they are not all public.
    MANIFEST_SOURCE_URL Defaults to the shared talentsuite-atlas manifest.
"""

from __future__ import annotations

import json
import os
import sys
from typing import Any

from check_dependabot_alerts import (
    API_URL,
    DEFAULT_MANIFEST_SOURCE_URL,
    CheckError,
    _api_request,
    fetch_manifest,
    manifest_repositories,
    parse_manifest_source_url,
    publish,
)


def fetch_topics(repository: str, token: str) -> list[str]:
    data, _ = _api_request("GET", f"{API_URL}/repos/{repository}", token)
    topics = data.get("topics") if isinstance(data, dict) else None
    if not isinstance(topics, list) or not all(isinstance(topic, str) for topic in topics):
        raise CheckError(f"Unexpected repository response for {repository}.")
    return sorted(topics)


def topics_document(repository: str, topics: list[str]) -> dict[str, Any]:
    return {"repository": repository, "topics": topics}


def topics_path(repository: str) -> str:
    return f"{repository.split('/')[-1]}/repo-topics/repo-topics.json"


def main() -> int:
    pr_token = os.environ.get("GITHUB_PR_TOKEN", "")
    if not pr_token:
        print("GITHUB_PR_TOKEN is required.", file=sys.stderr)
        return 1
    topics_token = os.environ.get("REPO_TOPICS_TOKEN", "") or pr_token
    manifest_source_url = os.environ.get("MANIFEST_SOURCE_URL", DEFAULT_MANIFEST_SOURCE_URL)
    target_repository, _ = parse_manifest_source_url(manifest_source_url)

    manifest = fetch_manifest(manifest_source_url)
    repositories = manifest_repositories(manifest)
    print(f"Loaded manifest with {len(repositories)} repositories.", file=sys.stderr)

    files: dict[str, bytes] = {}
    failures = []
    for repository in repositories:
        try:
            topics = fetch_topics(repository, topics_token)
            files[topics_path(repository)] = (json.dumps(topics_document(repository, topics), indent=2) + "\n").encode("utf-8")
            print(f"{repository}: {', '.join(topics) or '(no topics)'}", file=sys.stderr)
        except CheckError as error:
            failures.append({"repository": repository, "message": str(error)})
            print(f"{repository}: FAILED: {error}", file=sys.stderr)

    if not files:
        print("No topics fetched -- not publishing a PR.", file=sys.stderr)
        print(json.dumps({"failures": failures}, indent=2))
        return 1

    result = publish(
        target_repository,
        files,
        pr_token,
        title="Update repository topics",
        branch_prefix="repo-topics",
        body="Generated by scripts/fetch_repo_topics.py -- GitHub topics for every repository in the manifest.",
    )
    result["failures"] = failures
    print(json.dumps(result, indent=2))
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
